### ISSUE TITLE
The Status - "All Services Are Currently Active" Doesn't Work

### ISSUE THREAD

**Issue by Frazl** [redbrick/react-site#1]
This is just static text. I had great plans to pull information from somewhere but then got lazy. 

If anyone has known API endpoints for something like - https://status.redbrick.dcu.ie/ that would be perfect as it exists external to the RB ecosystem. 

The usefulness of this feature alone is questionable though as any status API hosted on Redbrick itself could go down and in turn the site wouldn't be great to display the status of Redbrick services.

**Comment by butlerx** [comment]
This Functionalist was added in #17 to enable it an api key needs to be added to the env variable at build time. 

We Could probably add docs for that.

**Comment by Frazl** [comment]
Yeah should probably update the readme & rb docs regarding that. Also the apache instructions are now deprecated. Will close this for now
